tango_with_django_project/rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^about/$',views.about,name='about'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/',views.add_page,name='add_page'),
        url(r'^add_category/',views.add_category,name='add_category'),
        url(r'^category/(?P<category_name_slug>[\w\-]+)/$',views.category,name='category'),
        url(r'^page/(?P<page_name_slug>[\w\-]+)/$',views.page,name='page')
        )

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_with_django_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls',namespace='rango')),

)
if settings.DEBUG:
	urlpatterns += patterns('django.views.static',
		(r'^media/(?P<path>.*)',
		'serve',
		{ 'document_root': settings.MEDIA_ROOT}),)

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
	"""docstring for Category"""
	name=models.CharField(max_length=128,unique=True)
	views=models.IntegerField(default=0)
	likes=models.IntegerField(default=0)
	slug=models.SlugField(default=' ')

	def save(self, *args, **kwargs):
		# Uncomment if you don't want the slug to change every time the name changes
        #if self.id is None:
             #self.slug = slugify(self.name)
		self.slug=slugify(self.name)
		super(Category,self).save(*args,**kwargs)    
	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name_plural= "Categories"
		
		
class Page(models.Model):
	"""docstring for Page"""
	category=models.ForeignKey(Category, on_delete= models.CASCADE)
	title=models.CharField(max_length=128)
	url=models.URLField()
	views=models.IntegerField(default=0)
	slug =models.SlugField(default='')

	def save(self,*args,**kwargs):
		self.slug=slugify(self.title)
		super(Page,self).save(*args,**kwargs)

	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name_plural= "Pages"

# Add a user profile
class UserProfile(models.Model):
	# Needed to UserProfile to User model instance
	user = models.OneToOneField(User)
	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to = 'profile_images',blank=True)

	def __unicode__(self):
		return self.user.username


		
		

		

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Category,Page, UserProfile

class CategoryForm(forms.ModelForm):
	name=forms.CharField(max_length=128,help_text="Please enter the category name.")
	views=forms.IntegerField(widget=forms.HiddenInput(),initial=0)
	likes=forms.IntegerField(widget=forms.HiddenInput(),initial=0)
	slug=forms.CharField(widget=forms.HiddenInput(),required=False)

	def clean(self):
		cleaned_data=super(CategoryForm,self).clean()
		name=cleaned_data.get('name')
		if name:
			raise forms.ValidationError("The name exist,enter different one.")
		elif name == ' ':
			raise forms.ValidationError(" Cannot submit an empty field ,enter a category")
		else:
			raise forms.ValidationError("Category does not exist")

		return cleaned_data

	class Meta:
		# Provide an association between the ModelForm and a model
		model=Category
		fields=('name',)

class PageForm(forms.ModelForm):
	title=forms.CharField(max_length=128,help_text="Please enter the title of the page.")
	url=forms.URLField(max_length=200,help_text="Please enter the url of the page.")
	views=forms.IntegerField(widget=forms.HiddenInput(),initial=0,required=False)
	slug=forms.CharField(widget=forms.HiddenInput(),required=False)

	def clean(self):
		cleaned_data=self.cleaned_data
		url=cleaned_data.get('url')
		# If url is not empty and doesn't start with 'http://', prepend 'http://'.
		if url and not url.startswith('https://'):
			url = ('https://') + url
			cleaned_data['url']=url
		return cleaned_data


	class Meta:
		model=Page
		exclude=('category',)
		# or specifify fields to include (i.e exclude 'category') e.g fields('title','url','views')

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model=User
		fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
	class Meta:
		model =UserProfile
		fields =('website','picture')

tango_with_django_project/rango/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Category,Page
from .forms import CategoryForm, PageForm

def index(request):
    context_dict={}
    try:
        # The inclusion of '-' sorts the values in descending order
        category_list=Category.objects.order_by('-likes')[:5]
        context_dict['categories']=category_list

        page_list=Page.objects.order_by('-views')[:5]
        context_dict['pages']=page_list
    except Exception as e:
        raise e
    
    return render(request, 'rango/index.html',context_dict)

def about(request):
	return render(request,'rango/about.html',{"aboutmessage" : "This is the about text from the about view"})

def category(request,category_name_slug):
	# Create a context dictionary which we can pass to the template rendering engine.
    context_dict = {}

    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # So the .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name
        context_dict['category_name_slug']=category.slug

        # Retrieve all of the associated pages.
        # Note that filter returns >= 1 model instance.
        pages = Page.objects.filter(category=category)

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything - the template displays the "no category" message for us.
        pass

    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context_dict)

def page(request,page_name_slug):
    context_dict={}
    try:
        pages=Category.objects.get(slug=page_name_slug)
        context_dict['page_title'] =pages.title
        context_dict['pages']=pages
    except Page.DoesNotExist:
        pass

    return render(request,'rango/page.html',context_dict)

def add_category(request):
    if request.method == 'POST':
        form=CategoryForm(request.POST)
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)
            # Now call the index() view.The user will be shown the homepage.
            return HttpResponseRedirect('/rango/')
        else:
            print (form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        form=CategoryForm()

    return render(request,'rango/add_category.html',{'form' : form})

def add_page(request, category_name_slug):

    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
                cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                # probably better to use a redirect here.
                return category(request, category_name_slug)
        else:
            print form.errors
    else:
        form = PageForm()

    context_dict = {'form':form, 'category': cat}

    return render(request, 'rango/add_page.html', context_dict)

tango_with_django_project/templates/rango/about.html
<!DOCTYPE html>
{% load static%}
<html>
<head>
	<title>About</title>
</head>
<body>
<p>Rango says ... <strong> {{aboutmessage}}</strong> <br> <a href="/rango/">Index</a> </p>
<p><img src="{% static 'http://res.cloudinary.com/mambobyad/image/upload/c_scale,h_500,w_450/v1496756903/profile_fjowfq.jpg'%}" alt="picture of Queen"></p>
</body>
</html>

tango_with_django_project/templates/rango/add_category.html
<!DOCTYPE html>
<html>
<head>
	<title>Rango</title>
</head>
<body>
<h1>Add Category</h1>
<form id="category_form" method="POST" action="rango/add_category/">
	{% csrf_token %}
	{% for hidden in form.hidden_fields%}
		{{ hidden }}
	{% endfor %}
	{% for field in form.visible_fields %}
		{{ field.errors}}
		{{ field.help_text}}
		{{ field }}
	{% endfor%}<br>
	<input type="submit" name="submit" value="create category">
	
</form>


</body>
</html>

tango_with_django_project/templates/rango/add_page.html
<!DOCTYPE html>
<html>
<head>
	<title>Add page</title>
</head>
<body>
	<h1> Add Page</h1>
	{% if category%}
	<form id="page_form" method="POST" action="rango/add_page/">
		{% csrf_token %}
		{% for hidden in form.hidden_fields%}
			{{ hidden }}
		{% endfor%}
		{% for field in form.visible_fields%}
		<p>
			{{ field.errors }}
			{{ field.help_text }}
			{{ field }}			
		</p>			
		{% endfor%}
		<input type="submit" name="submit" value="create page">
	</form>
	{% else%}
	<p> A category by this name does not exist</p>
	{% endif%}


</body>
</html>

tango_with_django_project/templates/rango/category.html
<!DOCTYPE html>
<html>
<head>
	<title>Rango</title>
</head>
<body>
	{% if category %}
	<h1> {{ category_name}} </h1>
	<p>
		{% if pages %}
		<ul>
			{% for page in pages %}
			<li><a href="{{ page.url }}"> {{page.title}}</a></li>
			{% endfor %}
		</ul>
		<a href="{% url 'rango:add_page' category_name_slug %}"> Add a new page</a>
		{% else %}
			<strong> No pages currently in category</strong>
		{% endif %}
	{% else %}
		The specified category {{ category_name }} does not exist
	{% endif %}
	</p>

</body>
</html>

tango_with_django_project/templates/rango/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Rango</title>
</head>
<body>
<h1>Rango says... Hello World</h1>
<p>
	{% if categories%}
	<ul>
		{% for category in categories%}
		 <!-- Following line changed to add an HTML hyperlink -->
		<li> <a href="{% url 'rango:category' category.slug%}"> {{ category.name}} </a></li>
		{% endfor%}
	</ul>
	{% else %}
	<strong> There are no categories present</strong> <br>
	{% endif %}
</p>
<p>
	<h2 style="color: blue"> Top five most viewed pages</h2>
	{% if pages%}
	<ul>
		{% for page in pages %}
		<li><a href="{{page.url}}">{{ page.title }} - {{ page.views }} views</a></li>
		{%endfor%}
	</ul>
	{% else %}
	<strong> There are no pages present </strong>
	{% endif%}
	<a href="{% url 'rango:about' %}">About</a><br>
	<a href="{% url 'rango:add_category' %}">Add a new category</a>
</p>
</body>
</html>

tango_with_django_project/templates/rango/page.html
<!DOCTYPE html>
<html>
<head>
	<title>Top five pages</title>
</head>
<body>
{% if pages %}
<h1> {{ page_title }}</h1>
<p>
	{% for page in pages%}
	<ul>
		<li><a href="{% url 'rango:page' page.slug%}">{{ page.title }}</a></li>
	</ul>
	{% endfor %}
</p>
{% else %}
<strong>Page does not exist</strong>
{% endif %}


</body>
</html>

tango_with_django_project/templates/rango/test.html
<!DOCTYPE html>
<html>
<head>
	<title>Nothing</title>
</head>
<body>
<form method="POST" action="test.html">
<p>
	Go:
	<input type="button" name="submit" placeholder="GO!"> <br>
</p>
<p>
	Write:
	<input type="text" name="Nothing" placeholder="Write something"><br>	
</p>
<p>
	<input type="radio" name="gender" required=""> male <br>
</p>
<p>
	<input type="radio" name="gender" required="">female <br>	
</p>
	
	
	
	
	
</form>

</body>
</html>